import type { BuilderConfig } from "./types";

export const builderConfig = {
  navbar: "classic",
  hero: "background",
  footer: "classic",
  sections: [
    {
      id: "about",
      type: "about",
      variant: "split",
      enabled: true,
      anchorName: "about",
    },
    {
      id: "text",
      type: "text",
      variant: "default",
      enabled: true,
      anchorName: "text",
    },
    {
      id: "skills",
      type: "skills",
      variant: "grid",
      enabled: true,
      anchorName: "skills",
    },
    {
      id: "items",
      type: "items",
      variant: "grid",
      enabled: true,
      anchorName: "projects",
    },
    {
      id: "menu",
      type: "menu",
      variant: "grid",
      enabled: true,
      anchorName: "menu",
    },
    {
      id: "experience",
      type: "experience",
      variant: "timeline",
      enabled: true,
      anchorName: "experience",
    },
    {
      id: "testimonials",
      type: "testimonials",
      variant: "grid",
      enabled: true,
      anchorName: "testimonials",
    },
    {
      id: "contact",
      type: "contact",
      variant: "default",
      enabled: true,
      anchorName: "contact",
    },
    {
      id: "features",
      type: "features",
      variant: "default",
      enabled: true,
      anchorName: "features",
    },
    {
      id: "pricing",
      type: "pricing",
      variant: "default",
      enabled: true,
      anchorName: "pricing",
    },
    {
      id: "faq",
      type: "faq",
      variant: "accordion",
      enabled: true,
      anchorName: "faq",
    },
    {
      id: "cta",
      type: "cta",
      variant: "simple",
      enabled: true,
      anchorName: "cta",
    },
    {
      id: "gallery",
      type: "gallery",
      variant: "grid",
      enabled: false,
      anchorName: "gallery",
    },
    {
      id: "form",
      type: "form",
      variant: "default",
      enabled: false,
      anchorName: "form",
    },
  ],
} satisfies BuilderConfig;
