import type { BuilderConfig } from "./types";

export const builderConfig = {
  navbar: "classic",
  hero: "background",
  footer: "classic",
  sections: [
    {
      id: "init-about",
      type: "about",
      variant: "split",
      enabled: true,
      anchorName: "about",
    },
    {
      id: "init-text",
      type: "text",
      variant: "default",
      enabled: true,
      anchorName: "text",
    },
    {
      id: "init-skills",
      type: "skills",
      variant: "grid",
      enabled: true,
      anchorName: "skills",
    },
    {
      id: "init-projects",
      type: "items",
      variant: "grid",
      enabled: true,
      anchorName: "projects",
    },
    {
      id: "init-menu",
      type: "menu",
      variant: "grid",
      enabled: true,
      anchorName: "menu",
    },
    {
      id: "init-experience",
      type: "experience",
      variant: "timeline",
      enabled: true,
      anchorName: "experience",
    },
    {
      id: "init-testimonials",
      type: "testimonials",
      variant: "grid",
      enabled: true,
      anchorName: "testimonials",
    },
    {
      id: "init-contact",
      type: "contact",
      variant: "default",
      enabled: true,
      anchorName: "contact",
    },
    {
      id: "init-features",
      type: "features",
      variant: "default",
      enabled: true,
      anchorName: "features",
    },
    {
      id: "init-pricing",
      type: "pricing",
      variant: "default",
      enabled: true,
      anchorName: "pricing",
    },
    {
      id: "init-faq",
      type: "faq",
      variant: "accordion",
      enabled: true,
      anchorName: "faq",
    },
    {
      id: "init-cta",
      type: "cta",
      variant: "simple",
      enabled: true,
      anchorName: "cta",
    },
  ],
} satisfies BuilderConfig;
